### ISSUE TITLE
Don't hard code Git branch name

### ISSUE THREAD

**Issue by mylo88** [monome-community/norns-community#10]
The page for [rebound](https://norns.community/rebound) is missing the contents of the project's [readme file](https://github.com/nf/rebound#readme).

I did some debugging and found that 02-build.py hardcodes the branch name `main`.  The rebound project has a `master` branch, but not a `main` branch (the repo was created before Github renamed the default branch to `main`).

Fix by using the remote head instead of a hard coded branch name.  In 02-build.py, change:

    github_raw_url_template = 'https://raw.githubusercontent.com/GITHUB_AUTHOR/GITHUB_PROJECT/main'

to: 

    github_raw_url_template = 'https://raw.githubusercontent.com/GITHUB_AUTHOR/GITHUB_PROJECT/HEAD'

**Comment by mylo88** [comment]
I am not the owner of the rebound project. 

More than 30% of the projects listed in community.norns do not use `main` as the default branch name.

It is common practice to use remote HEAD as the default branch.  That's what `git clone` uses.

The broader initiatives are generally about providing tools or making changes so developers can remove or avoid offensive terms. Requiring a developer to change a term in their project is above and beyond most of these initiatives.

**Comment by tyleretters** [comment]
hey! thanks you for surfacing this info. we discussed it and definitely did not realize 30% of the projects do not use `main`. also, please accept my apology for assuming this was your script.

this has been addressed in #11
