### ISSUE TITLE
doc links with /en/ in them are broken

### ISSUE THREAD

**Issue by dandante** [monome-community/norns-community#14]
Some script pages' documentation links have `/en/` in them ([example](https://norns.community/choukanzu)).
Clicking on those links gives a 404. But remove `/en` and the link works again. 

Example broken link: https://norns.community/en/authors/alanza/choukanzu
Example working link: https://norns.community/authors/alanza/choukanzu (redirects to https://norns.community/choukanzu )

**Comment by dandante** [comment]
Never mind. Something else is going on.

**Comment by tyleretters** [comment]
thanks for the issue report @dandante!! i'm going to re-open this as i think you're correct.

**Comment by dandante** [comment]
The reason I closed it is that the documentation link (when it works) takes you to the same script page, where there sometimes is no documentation. So I got a bit confused.

**Comment by tyleretters** [comment]
@dandante these are working now! thank you.
