### ISSUE TITLE
image code markdown not rendered

### ISSUE THREAD

**Issue by dtenenba** [monome-community/norns-community#15]
Have a look at the `oooooo` page on here:

https://norns.community/oooooo (scroll down to the `grid` section)

You'll see this:

<img width="888" alt="image" src="https://github.com/monome-community/norns-community/assets/2286826/6b3ed815-ca05-42c7-8b2d-a8ed8d732844">

The corresponding page on GitHub renders the grid images just fine:

https://github.com/schollz/oooooo/blob/main/README.md#grid

So I guess that something in the process of grabbing that page and rendering it is not working properly?

Thanks

**Comment by p3r7** [comment]
the issue is more about jekyll's markdown rendering engine mis-interpreting the pipe character (`|`), supported by github's for image options, as a table delimiter.

```
                ↓ here
![oooooo_grid-03|690x407](https://user-images.githubusercontent.com/6550035/132006771-4fdd4e9e-3a02-48e9-b94a-7f6454d60399.png) 
```

**Comment by dandante** [comment]
Thanks, I'll post an issue in the oooooo repo about this - hopefully using the jekyll syntax will work in both places, since github pages actually uses jekyll.

**Comment by p3r7** [comment]
mhm, i'm not sure. iirc github doesn't support this syntax.

the cleanest solution would be to rewrite those properties as they get imported in norns community. just a mater of regexp-foo.

**Comment by schollz** [comment]
I think Jekyll supports this? Ie switch kramdown to gfm: https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/setting-a-markdown-processor-for-your-github-pages-site-using-jekyll

Since the markdown is from GitHub readmes it makes sense to use gfm instead of conforming to kramdown

**Comment by p3r7** [comment]
oh rad, didn't knew this could be tweaked.

thanks!

**Comment by p3r7** [comment]
sorry, i've been busy w/ other stuff.

i plan to alternative renderers on a local copy on my machine (to prevent having to pollute the repo w/ more experimentations).

**Comment by tyleretters** [comment]
@p3r7 can i take a look?

**Comment by p3r7** [comment]
@tyleretters feel free to!

i haven't yet taken the time to upgrade my local jekyll container image to try. you'll certainly be way faster than me esp. if you have something ready to play with.

i hope my previous analysis is clear enough to be useful.

**Comment by schollz** [comment]
ah! that syntax [is discourse markdown](https://meta.discourse.org/t/markdown-for-image-resize-by-px-not-percent/108513), because I copied and pasted it into Github readme from a lines post I think.

I can just remove it

**Comment by tyleretters** [comment]
🔥
