### ISSUE TITLE
Documentation for l_ll__l_ by infinite digits leads to 404

### ISSUE THREAD

**Issue by bizzou** [monome-community/norns-community#16]
This [https://norns.community/en/authors/infinitedigits/l_ll__l_](https://norns.community/en/authors/infinitedigits/l_ll__l_) is supposed to lead to the documentation but is not found.

It is linked here: [https://norns.community/l_ll__l_](https://norns.community/l_ll__l_)

Thanks.

**Comment by tyleretters** [comment]
hey @bizzou thanks for opening this issue! i will look into getting the redirects working. (i thought we had solved for all these!)

**Comment by tyleretters** [comment]
@bizzou these are working now! thank you.
