### ISSUE TITLE
Github action for publishing broken

### ISSUE THREAD

**Issue by awwaiid** [monome-community/norns-community#21]
I think the scheduled activity for publishing community changes is broken. The [github action](https://github.com/monome-community/norns-community/actions/workflows/build.yml) says:

"This scheduled workflow is disabled because there hasn't been activity in this repository for at least 60 days. Enable this workflow to resume scheduled runs. "

**Comment by dndrks** [comment]
woop!! super good eye tysm!! i enabled the workflow and forced the action, @tyleretters / @tehn / @p3r7 does that seem like all that’s needed?

**Comment by tyleretters** [comment]
interesting. yeah sounds like a cost-management thing to prevent legions of zombie actions from running.... not sure what a fix is other than making sure "activity" happens on this repo every 59 days.

**Comment by Dewb** [comment]
I think the fix might be to remove the scheduled trigger. Running the action on push should be sufficient to keep the site updated, right?

**Comment by tyleretters** [comment]
@Dewb yes and we'd need "on push" from https://github.com/monome/norns-community as well. something like this: https://stackoverflow.com/questions/74775432/trigger-another-repo-in-github-actions

**Comment by tapecanvas** [comment]
Just popping in to bump this issue. Seems like the workflow was disabled again and no new scripts have been added to the page since early January.

**Comment by tyleretters** [comment]
thanks for the bump @tapecanvas. @dndrks just ran the action so everything should be showing up now

**Comment by tyleretters** [comment]
@dndrks @tehn what do you all think of adding an on push trigger as mentioned in https://github.com/monome-community/norns-community/issues/21#issuecomment-1872335032 ?

**Comment by tehn** [comment]
sounds good to me!

**Comment by dndrks** [comment]
seems like all's well now, so closing this issue!

**Comment by tyleretters** [comment]
it's actually not all well. i had to do a manual run a few days ago.

i think the least worst thing to do might be a cron job (eep) somewhere that runs the action nightly. this would solve for everything.

**Comment by tyleretters** [comment]
update: we tried out an action but it failed https://github.com/monome/norns-community/actions/runs/10640391017/job/29500011300

i'm researching next steps.

**Comment by tyleretters** [comment]
@Dewb and i were chatting and the idea came up to combine the repos.

i'm sharing because i think the pros outweigh the cons. basically we put the website in a `./docs` directory. a git submodule, perhaps.

whenever a merge happens the build runs. every night at midnight the build runs. odds of inactivity in increments greater than the github limit is unlikely.

keeping the repos orthogonal has a cost: github™️ personal access tokens don't feel right in the context of a communal project like norns. the other alternative is a cron job which adds sysadmin labor and (potential) hardcosts. (meta: github designed this product to not give away free cycles indefinitely, it makes business sense.)

the totally lateral solution is to just mark every 59 days on our calendars and make a game out of who can run the action first. not the worst, but i usually don't like being responsible for a dead nerds hand if i don't have to be. merging the repos is more resilient.

**Comment by tehn** [comment]
i think if it was a submodule, that'd be fine--- that way the PRs/issues/etc would have separate channels (this was the main con in my mind)

perhaps @ngwese has a strong opinion on this?

**Comment by ngwese** [comment]
i haven't had a chance to really wrap my head around what the setup is but if the primary goal is to trigger a website rebuild based on commits to this repository or based on commits to the catalog repository i'm wondering if it would make sense to add a pipeline in the catalog (on merge to main) which triggered a pipeline run in this repo.

https://medium.com/hostspaceng/triggering-workflows-in-another-repository-with-github-actions-4f581f8e0ceb

**Comment by tyleretters** [comment]
@tehn @ngwese i lack the organizational permissions to create & configure a PAT for monome repos. it needs to be an owner, i think. if this is the path we'd like to go down someone else needs to do the work:

1. generate PAT with the proper permissions
2. add PAT as a [repo secret](https://docs.github.com/en/actions/security-for-github-actions/security-guides/using-secrets-in-github-actions) to https://github.com/monome/norns-community
3. complete the steps in the [link @ngwese shared](https://medium.com/hostspaceng/triggering-workflows-in-another-repository-with-github-actions-4f581f8e0ceb). "step 2" is already started in the target repo [here](https://github.com/monome-community/norns-community/blob/main/.github/workflows/build.yml#L17-L20C9) with a dispatch action called `trigger_build_via_norns_community_merge`

![Screenshot 2024-10-02 at 09 30 05](https://github.com/user-attachments/assets/26f43f32-80d7-4e96-96d0-d13756097244)

**Comment by tehn** [comment]
added you as a maintainer, would be hyped if you were inclined to pursue
this improvement

**Comment by tyleretters** [comment]
this is resolved!

merges to `main` on [monome/norns-community](https://github.com/monome/norns-community/) now trigger deploys of https://norns.community.

for future reference / documentation:

- [base guide](https://medium.com/hostspaceng/triggering-workflows-in-another-repository-with-github-actions-4f581f8e0ceb)
- [here's the workflow on monome/norns-community](https://github.com/monome/norns-community/blob/main/.github/workflows/trigger-website-build.yml)
- it uses a PAT with read & write permissions on the "Content" type:

![Screenshot 2024-10-04 at 12 11 25](https://github.com/user-attachments/assets/32e7c68c-161a-4326-bf49-73d19bd6ee4f)

![Screenshot 2024-10-04 at 12 10 36](https://github.com/user-attachments/assets/1276e8c3-5810-48b4-a580-f2f2532a9a6d)


- the PAT is then stored as an action secret in `monome/norns-community`:

![Screenshot 2024-10-04 at 12 12 04](https://github.com/user-attachments/assets/2f91a601-6fa6-437b-ab8d-3cc1e153c66c)


- the max lifespan for a PAT is one year, so this will need to be cycled next october

**Comment by tehn** [comment]
thank you for figuring this out!

a somewhat comical stack of complexity to keep our tiny systems in sync. i appreciate your dedication to setting up smooth maintenance

**Comment by p3r7** [comment]
that's awesome @tyleretters !
