### ISSUE TITLE
Increase font size?

### ISSUE THREAD

**Issue by niksilver** [monome-community/norns-community#7]
This is subjective, but it seems the font size is rather small compared to similar sites. Here's a screenshot comparison from my brower - Firefox on Windows desktop, all sites at their default zoom level.

![comparison](https://github.com/monome-community/norns-community/assets/149467/8a07631b-da97-4df9-9e4c-b1f529c24e15)

URLs used for this:
* https://llllllll.co/t/tmi/40818
* https://github.com/schollz/tmi
* https://vaporwavemall.com/tmi

The font also seems small on my mobile device (the browser is Firefox on Android), but that's more fiddly to screenshot and compare.

**Comment by tyleretters** [comment]
final computed sizes:

- lines: `15.008px`
- github: `16px`
- norns.community: `12.8px`

the size was selected to match monome.org.

i defer to @tehn

**Comment by tehn** [comment]
this is interesting. i'm wondering if some of the sense of discontinuity is more about the font being fixed-width.

i'm using firefox on ubuntu and on android. i agree that on desktop the font is a _tiny_ bit smaller some other sites (but definitely not others, ie mastodon)--- but on android i think it's fine and making the font bigger would reduce line length to such a degree of hindering usability.

right now i'd like to punt/postpone and do more considering. hopefully individuals using browser zoom isn't seen as unreasonable. (on my system i have sites randomly tuned from 120% - 150%, and i use 130% as "default"

**Comment by tehn** [comment]
increased from 0.8em to 0.9em, thanks for the suggestion
