### ISSUE TITLE
project page: incorrect documentation image URLs for github-hosted zip file project URLs

### ISSUE THREAD

**Issue by andr-ew** [monome-community/norns-community#9]
thanks for all the wonderful work on the new site!

I'm getting missing images for all my projects that are using .zip files (via github) as the project/download URL. [heres](https://norns.community/ndls) an example (the project URL is `https://github.com/andr-ew/ndls/releases/download/latest/complete-source-code.zip`). 

for the first image on the page, I'm expecting this URL: 
```
https://raw.githubusercontent.com/andr-ew/ndls/main/lib/doc/ndls_overview.png
```
but getting this URL (a 404) : 
```
https://raw.githubusercontent.com/andr-ew/ndls/releases/download/latest/complete-source-code.zip/main/lib/doc/ndls_overview.png
```

the site is finding my `README.md`s just find though, so I suppose whatever magic is being used to find the README, just needs to carry over to the images :)

(for context, I'm distributing my scrips as .zips because maiden's UPDATE command (seemingly) updates the main repo only, and not subrepositories. zips are also nice for hosting easily installable version histories)

((P.S. my python is quite rusty, but happy to contribute time to a fix, just wanted to log here before diving in))

**Comment by tehn** [comment]
i propose we fix maiden instead. can you open an issue there?
